sudo: false
dist: xenial

language: go
go:
  - 1.21.0

services:
  - mysql

jobs:
  include:
    - name: "go-sqlsmith"
      stage: integration-test
      script:
        - make
        - make integration-test
